<a href="https://colab.research.google.com/github/Inbakumaran-1221/IDRA-/blob/main/Assignment_DAY_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Load the dataset
file_name = "Day8_Ecommerce_Sales_Dataset.csv"
df = pd.read_csv(file_name)

print("E-Commerce Sales Dataset")
display(df.head())


# 1. Basic Information

print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)


# 2. Data Selection

print("\nSelected Columns:")
display(df[["Order_ID", "Customer", "Product", "Total_Sales"]].head())

print("\nDetails of First Order:")
display(df.iloc[0])


# 3. Filtering Data

print("\nOrders with Sales Greater Than 5000:")
high_sales = df[df["Total_Sales"] > 5000]
display(high_sales)

print("\nOrders with Quantity Greater Than 3:")
high_quantity = df[df["Quantity"] > 3]
display(high_quantity)

print("\nUPI Payment Orders:")
upi_orders = df[df["Payment_Method"] == "UPI"]
display(upi_orders)

print("\nElectronics Category Orders:")
electronics_orders = df[df["Category"] == "Electronics"]
display(electronics_orders)


# 4. Sorting Data

print("\nTop 10 Orders by Sales:")
top_orders = df.sort_values("Total_Sales", ascending=False).head(10)
display(top_orders[["Order_ID", "Product", "Category", "Total_Sales"]])

print("\nOrders with Lowest Sales:")
lowest_orders = df.sort_values("Total_Sales").head(10)
display(lowest_orders[["Order_ID", "Product", "Category", "Total_Sales"]])

print("\nTop Products by Quantity Sold:")
top_quantity = df.sort_values("Quantity", ascending=False).head(10)
display(top_quantity[["Product", "Quantity", "Total_Sales"]])


# 5. Overall Sales Statistics

total_sales = df["Total_Sales"].sum()
average_sales = df["Total_Sales"].mean()
highest_sales = df["Total_Sales"].max()
lowest_sales = df["Total_Sales"].min()
total_quantity = df["Quantity"].sum()
number_of_orders = df["Order_ID"].nunique()

print("\n===== Overall Sales Statistics =====")
print(f"Total Sales: ₹{total_sales:.2f}")
print(f"Average Sales per Order: ₹{average_sales:.2f}")
print(f"Highest Sale: ₹{highest_sales:.2f}")
print(f"Lowest Sale: ₹{lowest_sales:.2f}")
print(f"Total Quantity Sold: {total_quantity}")
print(f"Number of Orders: {number_of_orders}")


# 6. Category Wise Analysis

category_sales = df.groupby("Category")["Total_Sales"].agg(
    ["sum", "mean", "count"]
).sort_values("sum", ascending=False)

category_sales.columns = ["Total Sales", "Average Sales", "Number of Orders"]

print("\n===== Category Wise Sales =====")
display(category_sales)

category_quantity = df.groupby("Category")["Quantity"].sum().sort_values(
    ascending=False
)

print("\n===== Category Wise Quantity Sold =====")
display(category_quantity)


# 7. City Wise Analysis

city_sales = df.groupby("City")["Total_Sales"].agg(
    ["sum", "mean", "count"]
).sort_values("sum", ascending=False)

city_sales.columns = ["Total Sales", "Average Sales", "Number of Orders"]

print("\n===== City Wise Sales =====")
display(city_sales)


# 8. Product Wise Analysis

product_sales = df.groupby("Product")["Total_Sales"].agg(
    ["sum", "mean", "count"]
).sort_values("sum", ascending=False)

product_sales.columns = ["Total Sales", "Average Sales", "Number of Orders"]

print("\n===== Product Wise Sales =====")
display(product_sales)


# Top 10 Products
print("\n===== Top 10 Products by Sales =====")
display(product_sales.head(10))


# 9. Payment Method Analysis

payment_sales = df.groupby("Payment_Method")["Total_Sales"].agg(
    ["sum", "mean", "count"]
).sort_values("sum", ascending=False)

payment_sales.columns = ["Total Sales", "Average Sales", "Number of Orders"]

print("\n===== Payment Method Analysis =====")
display(payment_sales)


# 10. Region Wise Analysis

region_sales = df.groupby("Region")["Total_Sales"].agg(
    ["sum", "mean", "count"]
).sort_values("sum", ascending=False)

region_sales.columns = ["Total Sales", "Average Sales", "Number of Orders"]

print("\n===== Region Wise Sales =====")
display(region_sales)


# 11. Find Specific Orders

print("\nOrders with Sales Between ₹3000 and ₹7000:")
selected_orders = df[
    (df["Total_Sales"] >= 3000) &
    (df["Total_Sales"] <= 7000)
]

display(
    selected_orders[
        ["Order_ID", "Customer", "Product", "Total_Sales"]
    ]
)


print("\nOrders with Rating Above 4.5:")
high_rated_orders = df[df["Rating"] > 4.5]

display(
    high_rated_orders[
        ["Order_ID", "Customer", "Product", "Rating", "Total_Sales"]
    ]
)


# 12. Highest Selling Order

highest_order = df.loc[df["Total_Sales"].idxmax()]

print("\n===== Highest Selling Order =====")
print(f"Order ID: {highest_order['Order_ID']}")
print(f"Customer: {highest_order['Customer']}")
print(f"Product: {highest_order['Product']}")
print(f"Category: {highest_order['Category']}")
print(f"City: {highest_order['City']}")
print(f"Sales: ₹{highest_order['Total_Sales']:.2f}")


# 13. Product with Highest Total Sales

best_product = df.groupby("Product")["Total_Sales"].sum().idxmax()
best_product_sales = df.groupby("Product")["Total_Sales"].sum().max()

print("\n===== Best Performing Product =====")
print(f"Product: {best_product}")
print(f"Total Sales: ₹{best_product_sales:.2f}")


# 14. Best Performing Category

best_category = df.groupby("Category")["Total_Sales"].sum().idxmax()
best_category_sales = df.groupby("Category")["Total_Sales"].sum().max()

print("\n===== Best Performing Category =====")
print(f"Category: {best_category}")
print(f"Total Sales: ₹{best_category_sales:.2f}")


# 15. Most Used Payment Method

popular_payment = df["Payment_Method"].value_counts().idxmax()
payment_count = df["Payment_Method"].value_counts().max()

print("\n===== Most Used Payment Method =====")
print(f"Payment Method: {popular_payment}")
print(f"Number of Orders: {payment_count}")


# 16. Basic Observations

city_total = df.groupby("City")["Total_Sales"].sum()
top_city = city_total.idxmax()

category_total = df.groupby("Category")["Total_Sales"].sum()
top_category = category_total.idxmax()

product_total = df.groupby("Product")["Total_Sales"].sum()
top_product = product_total.idxmax()

payment_count = df["Payment_Method"].value_counts()
top_payment = payment_count.idxmax()

print("\n========== KEY OBSERVATIONS ==========")

print(f"1. The dataset contains {len(df)} orders and {len(df.columns)} columns.")

print(
    f"2. Total sales generated from all orders is "
    f"₹{total_sales:.2f}."
)

print(
    f"3. The highest performing category based on total sales is "
    f"{top_category}."
)

print(
    f"4. The product with the highest total sales is "
    f"{top_product}."
)

print(
    f"5. The city with the highest total sales is "
    f"{top_city}."
)

print(
    f"6. {top_payment} is the most commonly used payment method."
)

print(
    f"7. The average value of an order is "
    f"₹{average_sales:.2f}."
)

print(
    f"8. A total of {total_quantity} items were sold across "
    f"{number_of_orders} orders."
)

E-Commerce Sales Dataset

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

Dataset Shape: (100, 13)

Columns:
['Order_ID', 'Order_Date', 'Customer', 'City', 'Region', 'Category', 'Product', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Total_Sales', 'Rating', 'Payment_Method']

Data Types:
Order_ID              int64
Order_Date           object
Customer             object
City                 object
Region               object
Category             object
Product              object
Quantity              int64
Unit_Price            int64
Discount_Percent      int64
Total_Sales         float64
Rating              float64
Payment_Method       object
dtype: object

Selected Columns:

   Order_ID      Customer              Product  Total_Sales
0      1001     Kabir Ali  Wireless Headphones      4497.00
1      1002  Aditya Verma        Running Shoes      2799.00
2      1003    Sara Ahmed           Power Bank      2038.30
3      1004     Kabir Ali  Mechanical Keyboard      9496.20
4      1005   Priya Menon          Smart Watch      3134.05

Details of First Order:

Order_ID                           1001
Order_Date                   2026-02-27
Customer                      Kabir Ali
City                          Hyderabad
Region                            South
Category                    Electronics
Product             Wireless Headphones
Quantity                              3
Unit_Price                         1499
Discount_Percent                      0
Total_Sales                      4497.0
Rating                              3.8
Payment_Method         Cash on Delivery
Name: 0, dtype: object

Orders with Sales Greater Than 5000:

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
7,1008,2026-04-27,Aman Kumar,Jammu,North,Clothing,Hoodie,4,1599,5,6076.20,4.3,Credit Card
9,1010,2026-03-11,Aman Kumar,Kochi,South,Clothing,Jacket,4,2499,10,8996.40,4.7,Credit Card
10,1011,2026-03-22,Rahul Das,Hyderabad,South,Home & Kitchen,Coffee Maker,2,3499,0,6998.00,4.2,UPI
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
13,1014,2026-02-05,Dev Patel,Jaipur,North,Sports,Running Shoes,3,2799,0,8397.00,4.6,UPI
16,1017,2026-03-17,Sana Malik,Hyderabad,South,Sports,Cricket Bat,3,2499,0,7497.00,4.0,Net Banking
18,1019,2026-05-19,Reyansh Jain,Chennai,South,Clothing,Jacket,3,2499,0,7497.00,4.7,UPI
27,1028,2026-04-19,Sana Malik,Chandigarh,North,Electronics,Wireless Headphones,4,1499,5,5696.20,4.6,UPI
28,1029,2026-01-28,Sara Ahmed,Hyderabad,South,Electronics,Wireless Headphones,4,1499,5,5696.20,4.1,Credit Card
32,1033,2026-06-28,Maryam Khan,Pune,West,Home & Kitchen,Mixer Grinder,3,2999,10,8097.30,4.7,Net Banking
37,1038,2026-03-08,Aditya Verma,Pune,West,Sports,Dumbbell Set,5,1999,5,9495.25,5.0,Debit Card
38,1039,2026-04-28,Vivaan Kapoor,Chandigarh,North,Home & Kitchen,Mixer Grinder,2,2999,5,5698.10,3.8,UPI
40,1041,2026-03-14,Ishita Gupta,Delhi,North,Home & Kitchen,Coffee Maker,2,3499,5,6648.10,4.6,Cash on Delivery
47,1048,2026-06-24,Sara Ahmed,Lucknow,North,Home & Kitchen,Coffee Maker,3,3499,0,10497.00,5.0,UPI
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
50,1051,2026-04-28,Aisha Mir,Bhubaneswar,East,Electronics,Smart Watch,2,3299,0,6598.00,4.2,Credit Card
51,1052,2026-03-13,Rohan Mehta,Chandigarh,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.2,Debit Card
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
56,1057,2026-03-21,Alina Shah,Chennai,South,Home & Kitchen,Coffee Maker,3,3499,15,8922.45,4.5,Debit Card
58,1059,2026-01-01,Mehak Bhat,Chennai,South,Sports,Cricket Bat,4,2499,15,8496.60,4.2,Credit Card
59,1060,2026-04-24,Karan Joshi,Pune,West,Sports,Dumbbell Set,3,1999,10,5397.30,5.0,Credit Card
61,1062,2026-02-20,Kabir Ali,Mumbai,West,Electronics,Mechanical Keyboard,3,2499,0,7497.00,3.5,UPI
65,1066,2026-06-20,Dev Patel,Jaipur,North,Electronics,Smart Watch,2,3299,10,5938.20,4.7,Cash on Delivery
69,1070,2026-06-30,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,3.8,Net Banking
75,1076,2026-04-29,Ishita Gupta,Chennai,South,Electronics,Wireless Headphones,4,1499,0,5996.00,3.5,Debit Card
76,1077,2026-03-28,Reyansh Jain,Pune,West,Home & Kitchen,Electric Kettle,4,1499,5,5696.20,4.5,Debit Card
79,1080,2026-05-25,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,4.6,Debit Card
80,1081,2026-01-30,Reyansh Jain,Kolkata,East,Home & Kitchen,Electric Kettle,5,1499,15,6370.75,4.0,Debit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
92,1093,2026-05-16,Aisha Mir,Hyderabad,South,Sports,Cricket Bat,4,2499,15,8496.60,4.5,Cash on Delivery
93,1094,2026-03-06,Sara Ahmed,Mumbai,West,Home & Kitchen,Mixer Grinder,3,2999,5,8547.15,3.8,Credit Card
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking

Orders with Quantity Greater Than 3:

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
7,1008,2026-04-27,Aman Kumar,Jammu,North,Clothing,Hoodie,4,1599,5,6076.20,4.3,Credit Card
9,1010,2026-03-11,Aman Kumar,Kochi,South,Clothing,Jacket,4,2499,10,8996.40,4.7,Credit Card
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
15,1016,2026-03-06,Manya Rao,Pune,West,Books,The Alchemist,4,499,15,1696.60,3.5,UPI
24,1025,2026-01-02,Rohan Mehta,Chennai,South,Sports,Football,5,799,0,3995.00,5.0,UPI
26,1027,2026-05-02,Sara Ahmed,Chandigarh,North,Sports,Football,5,799,15,3395.75,4.6,Net Banking
27,1028,2026-04-19,Sana Malik,Chandigarh,North,Electronics,Wireless Headphones,4,1499,5,5696.20,4.6,UPI
28,1029,2026-01-28,Sara Ahmed,Hyderabad,South,Electronics,Wireless Headphones,4,1499,5,5696.20,4.1,Credit Card
29,1030,2026-03-13,Karan Joshi,Bengaluru,South,Books,Python Programming,4,749,0,2996.00,4.1,UPI
37,1038,2026-03-08,Aditya Verma,Pune,West,Sports,Dumbbell Set,5,1999,5,9495.25,5.0,Debit Card
41,1042,2026-06-20,Manya Rao,Kochi,South,Home & Kitchen,Water Bottle,5,699,0,3495.00,4.2,UPI
45,1046,2026-01-03,Ananya Singh,Delhi,North,Books,The Alchemist,4,499,15,1696.60,3.8,Credit Card
46,1047,2026-02-07,Sana Malik,Bengaluru,South,Electronics,Wireless Mouse,5,899,15,3820.75,4.0,UPI
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
49,1050,2026-03-10,Ishita Gupta,Srinagar,North,Clothing,T-Shirt,4,799,0,3196.00,3.8,Net Banking
51,1052,2026-03-13,Rohan Mehta,Chandigarh,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.2,Debit Card
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
54,1055,2026-02-18,Arjun Nair,Chennai,South,Sports,Yoga Mat,4,899,15,3056.60,3.5,Net Banking
58,1059,2026-01-01,Mehak Bhat,Chennai,South,Sports,Cricket Bat,4,2499,15,8496.60,4.2,Credit Card
63,1064,2026-02-07,Aman Kumar,Kochi,South,Books,Atomic Habits,4,599,0,2396.00,3.5,UPI
66,1067,2026-05-21,Karan Joshi,Mumbai,West,Books,The Alchemist,5,499,10,2245.50,4.0,Net Banking
69,1070,2026-06-30,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,3.8,Net Banking
70,1071,2026-01-16,Aditya Verma,Pune,West,Home & Kitchen,Water Bottle,4,699,10,2516.40,4.5,Net Banking
71,1072,2026-05-03,Aarav Sharma,Jaipur,North,Sports,Yoga Mat,5,899,10,4045.50,4.3,Debit Card
72,1073,2026-06-04,Sara Ahmed,Kolkata,East,Books,Atomic Habits,5,599,15,2545.75,4.6,Credit Card
75,1076,2026-04-29,Ishita Gupta,Chennai,South,Electronics,Wireless Headphones,4,1499,0,5996.00,3.5,Debit Card
76,1077,2026-03-28,Reyansh Jain,Pune,West,Home & Kitchen,Electric Kettle,4,1499,5,5696.20,4.5,Debit Card
79,1080,2026-05-25,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,4.6,Debit Card
80,1081,2026-01-30,Reyansh Jain,Kolkata,East,Home & Kitchen,Electric Kettle,5,1499,15,6370.75,4.0,Debit Card
83,1084,2026-06-19,Aisha Mir,Kolkata,East,Electronics,Wireless Mouse,5,899,10,4045.50,3.8,Cash on Delivery
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
86,1087,2026-03-10,Vivaan Kapoor,Kolkata,East,Books,Atomic Habits,4,599,15,2036.60,4.1,UPI
87,1088,2026-06-06,Alina Shah,Lucknow,North,Books,Python Programming,4,749,15,2546.60,4.5,Debit Card
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
90,1091,2026-06-26,Hiba Sheikh,Kochi,South,Books,Atomic Habits,5,599,0,2995.00,5.0,Net Banking
92,1093,2026-05-16,Aisha Mir,Hyderabad,South,Sports,Cricket Bat,4,2499,15,8496.60,4.5,Cash on Delivery
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card

UPI Payment Orders:

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI
10,1011,2026-03-22,Rahul Das,Hyderabad,South,Home & Kitchen,Coffee Maker,2,3499,0,6998.00,4.2,UPI
13,1014,2026-02-05,Dev Patel,Jaipur,North,Sports,Running Shoes,3,2799,0,8397.00,4.6,UPI
14,1015,2026-06-24,Sana Malik,Kolkata,East,Electronics,Wireless Headphones,2,1499,0,2998.00,4.8,UPI
15,1016,2026-03-06,Manya Rao,Pune,West,Books,The Alchemist,4,499,15,1696.60,3.5,UPI
18,1019,2026-05-19,Reyansh Jain,Chennai,South,Clothing,Jacket,3,2499,0,7497.00,4.7,UPI
19,1020,2026-04-03,Mehak Bhat,Chennai,South,Home & Kitchen,Mixer Grinder,1,2999,0,2999.00,4.1,UPI
23,1024,2026-02-27,Rohan Mehta,Jaipur,North,Sports,Running Shoes,1,2799,0,2799.00,4.3,UPI
24,1025,2026-01-02,Rohan Mehta,Chennai,South,Sports,Football,5,799,0,3995.00,5.0,UPI
27,1028,2026-04-19,Sana Malik,Chandigarh,North,Electronics,Wireless Headphones,4,1499,5,5696.20,4.6,UPI
29,1030,2026-03-13,Karan Joshi,Bengaluru,South,Books,Python Programming,4,749,0,2996.00,4.1,UPI
31,1032,2026-01-16,Ishita Gupta,Pune,West,Books,Atomic Habits,2,599,10,1078.20,4.5,UPI
33,1034,2026-05-29,Maryam Khan,Delhi,North,Clothing,T-Shirt,2,799,0,1598.00,4.7,UPI
36,1037,2026-06-02,Zoya Khan,Pune,West,Electronics,Power Bank,2,1199,15,2038.30,4.8,UPI
38,1039,2026-04-28,Vivaan Kapoor,Chandigarh,North,Home & Kitchen,Mixer Grinder,2,2999,5,5698.10,3.8,UPI
41,1042,2026-06-20,Manya Rao,Kochi,South,Home & Kitchen,Water Bottle,5,699,0,3495.00,4.2,UPI
43,1044,2026-05-10,Hiba Sheikh,Chennai,South,Clothing,T-Shirt,2,799,5,1518.10,4.2,UPI
46,1047,2026-02-07,Sana Malik,Bengaluru,South,Electronics,Wireless Mouse,5,899,15,3820.75,4.0,UPI
47,1048,2026-06-24,Sara Ahmed,Lucknow,North,Home & Kitchen,Coffee Maker,3,3499,0,10497.00,5.0,UPI
61,1062,2026-02-20,Kabir Ali,Mumbai,West,Electronics,Mechanical Keyboard,3,2499,0,7497.00,3.5,UPI
63,1064,2026-02-07,Aman Kumar,Kochi,South,Books,Atomic Habits,4,599,0,2396.00,3.5,UPI
68,1069,2026-03-27,Vivaan Kapoor,Ahmedabad,West,Electronics,Wireless Mouse,2,899,5,1708.10,4.7,UPI
77,1078,2026-01-05,Maryam Khan,Kolkata,East,Books,Machine Learning Basics,1,999,10,899.10,4.7,UPI
86,1087,2026-03-10,Vivaan Kapoor,Kolkata,East,Books,Atomic Habits,4,599,15,2036.60,4.1,UPI
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
98,1099,2026-03-06,Hiba Sheikh,Ahmedabad,West,Books,Machine Learning Basics,2,999,0,1998.00,3.8,UPI

Electronics Category Orders:

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI
14,1015,2026-06-24,Sana Malik,Kolkata,East,Electronics,Wireless Headphones,2,1499,0,2998.00,4.8,UPI
25,1026,2026-05-12,Sara Ahmed,Chandigarh,North,Electronics,Wireless Headphones,3,1499,0,4497.00,4.2,Net Banking
27,1028,2026-04-19,Sana Malik,Chandigarh,North,Electronics,Wireless Headphones,4,1499,5,5696.20,4.6,UPI
28,1029,2026-01-28,Sara Ahmed,Hyderabad,South,Electronics,Wireless Headphones,4,1499,5,5696.20,4.1,Credit Card
36,1037,2026-06-02,Zoya Khan,Pune,West,Electronics,Power Bank,2,1199,15,2038.30,4.8,UPI
46,1047,2026-02-07,Sana Malik,Bengaluru,South,Electronics,Wireless Mouse,5,899,15,3820.75,4.0,UPI
50,1051,2026-04-28,Aisha Mir,Bhubaneswar,East,Electronics,Smart Watch,2,3299,0,6598.00,4.2,Credit Card
51,1052,2026-03-13,Rohan Mehta,Chandigarh,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.2,Debit Card
61,1062,2026-02-20,Kabir Ali,Mumbai,West,Electronics,Mechanical Keyboard,3,2499,0,7497.00,3.5,UPI
65,1066,2026-06-20,Dev Patel,Jaipur,North,Electronics,Smart Watch,2,3299,10,5938.20,4.7,Cash on Delivery
68,1069,2026-03-27,Vivaan Kapoor,Ahmedabad,West,Electronics,Wireless Mouse,2,899,5,1708.10,4.7,UPI
75,1076,2026-04-29,Ishita Gupta,Chennai,South,Electronics,Wireless Headphones,4,1499,0,5996.00,3.5,Debit Card
83,1084,2026-06-19,Aisha Mir,Kolkata,East,Electronics,Wireless Mouse,5,899,10,4045.50,3.8,Cash on Delivery
91,1092,2026-04-14,Nikhil Sood,Ahmedabad,West,Electronics,Wireless Headphones,3,1499,0,4497.00,4.1,Debit Card
94,1095,2026-02-25,Maryam Khan,Mumbai,West,Electronics,Power Bank,2,1199,0,2398.00,4.6,Debit Card

Top 10 Orders by Sales:

    Order_ID              Product        Category  Total_Sales
48      1049        Running Shoes          Sports     13995.00
52      1053        Running Shoes          Sports     13295.25
84      1085         Coffee Maker  Home & Kitchen     12596.40
89      1090          Cricket Bat          Sports     12495.00
12      1013               Jacket        Clothing     10620.75
47      1048         Coffee Maker  Home & Kitchen     10497.00
69      1070               Jacket        Clothing      9996.00
79      1080               Jacket        Clothing      9996.00
51      1052  Mechanical Keyboard     Electronics      9496.20
3       1004  Mechanical Keyboard     Electronics      9496.20

Orders with Lowest Sales:

    Order_ID                  Product  Category  Total_Sales
5       1006            The Alchemist     Books       449.10
62      1063            The Alchemist     Books       449.10
73      1074            Atomic Habits     Books       539.10
96      1097                  T-Shirt  Clothing       679.15
60      1061       Python Programming     Books       711.55
82      1083                 Football    Sports       759.05
30      1031                 Yoga Mat    Sports       764.15
42      1043                  T-Shirt  Clothing       799.00
20      1021                 Yoga Mat    Sports       809.10
77      1078  Machine Learning Basics     Books       899.10

Top Products by Quantity Sold:

                  Product  Quantity  Total_Sales
26               Football         5      3395.75
24               Football         5      3995.00
12                 Jacket         5     10620.75
37           Dumbbell Set         5      9495.25
71               Yoga Mat         5      4045.50
72          Atomic Habits         5      2545.75
80        Electric Kettle         5      6370.75
83         Wireless Mouse         5      4045.50
95           Dumbbell Set         5      9495.25
99  Data Science Handbook         5      4495.00

===== Overall Sales Statistics =====
Total Sales: ₹447262.95
Average Sales per Order: ₹4472.63
Highest Sale: ₹13995.00
Lowest Sale: ₹449.10
Total Quantity Sold: 294
Number of Orders: 100

===== Category Wise Sales =====

                Total Sales  Average Sales  Number of Orders
Category
Sports            136026.45    5441.058000                25
Home & Kitchen    113329.90    5396.661905                21
Electronics        92086.00    4846.631579                19
Clothing           69028.20    4930.585714                14
Books              36792.40    1752.019048                21

===== Category Wise Quantity Sold =====

Category
Sports            79
Books             60
Home & Kitchen    59
Electronics       57
Clothing          39
Name: Quantity, dtype: int64

===== City Wise Sales =====

             Total Sales  Average Sales  Number of Orders
City
Hyderabad       59076.45    8439.492857                 7
Chennai         47493.20    4749.320000                10
Lucknow         46194.65    7699.108333                 6
Pune            41908.55    4190.855000                10
Mumbai          41457.80    5182.225000                 8
Kochi           37257.50    4139.722222                 9
Chandigarh      34539.65    4317.456250                 8
Delhi           30882.80    5147.133333                 6
Jaipur          25534.00    3647.714286                 7
Kolkata         20169.00    2881.285714                 7
Jammu           16059.75    2676.625000                 6
Ahmedabad       14788.70    2464.783333                 6
Bengaluru       13524.30    3381.075000                 4
Srinagar        11778.60    2355.720000                 5
Bhubaneswar      6598.00    6598.000000                 1

===== Product Wise Sales =====

                         Total Sales  Average Sales  Number of Orders
Product
Coffee Maker                51610.25    7372.892857                 7
Jacket                      47106.15    9421.230000                 5
Cricket Bat                 41483.40    8296.680000                 5
Running Shoes               41285.25    8257.050000                 5
Wireless Headphones         33877.40    4839.628571                 7
Dumbbell Set                30184.90    6036.980000                 5
Mechanical Keyboard         26489.40    8829.800000                 3
Electric Kettle             26382.40    5276.480000                 5
Mixer Grinder               25341.55    6335.387500                 4
Smart Watch                 15670.25    5223.416667                 3
Yoga Mat                    12765.80    2127.633333                 6
Atomic Habits               11590.65    1931.775000                 6
Football                    10307.10    2576.775000                 4
Water Bottle                 9995.70    1999.140000                 5
Wireless Mouse               9574.35    3191.450000                 3
T-Shirt                      7790.25    1558.050000                 5
Hoodie                       7675.20    3837.600000                 2
Python Programming           7527.45    1881.862500                 4
The Alchemist                7485.00    1247.500000                 6
Power Bank                   6474.60    2158.200000                 3
Jeans                        6456.60    3228.300000                 2
Machine Learning Basics      5694.30    1423.575000                 4
Data Science Handbook        4495.00    4495.000000                 1

===== Top 10 Products by Sales =====

                     Total Sales  Average Sales  Number of Orders
Product
Coffee Maker            51610.25    7372.892857                 7
Jacket                  47106.15    9421.230000                 5
Cricket Bat             41483.40    8296.680000                 5
Running Shoes           41285.25    8257.050000                 5
Wireless Headphones     33877.40    4839.628571                 7
Dumbbell Set            30184.90    6036.980000                 5
Mechanical Keyboard     26489.40    8829.800000                 3
Electric Kettle         26382.40    5276.480000                 5
Mixer Grinder           25341.55    6335.387500                 4
Smart Watch             15670.25    5223.416667                 3

===== Payment Method Analysis =====

                  Total Sales  Average Sales  Number of Orders
Payment_Method
Credit Card         106540.25    4842.738636                22
Debit Card           98064.90    4903.245000                20
Net Banking          96371.25    5668.897059                17
UPI                  96163.25    3698.586538                26
Cash on Delivery     50123.30    3341.553333                15

===== Region Wise Sales =====

        Total Sales  Average Sales  Number of Orders
Region
North     164989.45    4341.827632                38
South     157351.45    5245.048333                30
West       98155.05    4089.793750                24
East       26767.00    3345.875000                 8

Orders with Sales Between ₹3000 and ₹7000:

    Order_ID       Customer                Product  Total_Sales
0       1001      Kabir Ali    Wireless Headphones      4497.00
4       1005    Priya Menon            Smart Watch      3134.05
7       1008     Aman Kumar                 Hoodie      6076.20
8       1009     Aman Kumar        Electric Kettle      4497.00
10      1011      Rahul Das           Coffee Maker      6998.00
11      1012     Aman Kumar            Cricket Bat      4498.20
24      1025    Rohan Mehta               Football      3995.00
25      1026     Sara Ahmed    Wireless Headphones      4497.00
26      1027     Sara Ahmed               Football      3395.75
27      1028     Sana Malik    Wireless Headphones      5696.20
28      1029     Sara Ahmed    Wireless Headphones      5696.20
38      1039  Vivaan Kapoor          Mixer Grinder      5698.10
40      1041   Ishita Gupta           Coffee Maker      6648.10
41      1042      Manya Rao           Water Bottle      3495.00
46      1047     Sana Malik         Wireless Mouse      3820.75
49      1050   Ishita Gupta                T-Shirt      3196.00
50      1051      Aisha Mir            Smart Watch      6598.00
54      1055     Arjun Nair               Yoga Mat      3056.60
55      1056    Rohan Mehta           Dumbbell Set      3798.10
59      1060    Karan Joshi           Dumbbell Set      5397.30
65      1066      Dev Patel            Smart Watch      5938.20
67      1068     Aman Kumar        Electric Kettle      3822.45
71      1072   Aarav Sharma               Yoga Mat      4045.50
74      1075   Aarav Sharma                  Jeans      3228.30
75      1076   Ishita Gupta    Wireless Headphones      5996.00
76      1077   Reyansh Jain        Electric Kettle      5696.20
80      1081   Reyansh Jain        Electric Kettle      6370.75
83      1084      Aisha Mir         Wireless Mouse      4045.50
85      1086     Arjun Nair                  Jeans      3228.30
91      1092    Nikhil Sood    Wireless Headphones      4497.00
97      1098      Yusuf Dar        Electric Kettle      5996.00
99      1100      Kabir Ali  Data Science Handbook      4495.00

Orders with Rating Above 4.5:

    Order_ID       Customer                  Product  Rating  Total_Sales
2       1003     Sara Ahmed               Power Bank     4.6      2038.30
9       1010     Aman Kumar                   Jacket     4.7      8996.40
11      1012     Aman Kumar              Cricket Bat     4.6      4498.20
12      1013    Maryam Khan                   Jacket     4.8     10620.75
13      1014      Dev Patel            Running Shoes     4.6      8397.00
14      1015     Sana Malik      Wireless Headphones     4.8      2998.00
18      1019   Reyansh Jain                   Jacket     4.7      7497.00
20      1021   Reyansh Jain                 Yoga Mat     4.7       809.10
24      1025    Rohan Mehta                 Football     5.0      3995.00
26      1027     Sara Ahmed                 Football     4.6      3395.75
27      1028     Sana Malik      Wireless Headphones     4.6      5696.20
32      1033    Maryam Khan            Mixer Grinder     4.7      8097.30
33      1034    Maryam Khan                  T-Shirt     4.7      1598.00
34      1035      Dev Patel             Coffee Maker     4.7      2974.15
35      1036    Rohan Mehta                 Yoga Mat     5.0      1798.00
36      1037      Zoya Khan               Power Bank     4.8      2038.30
37      1038   Aditya Verma             Dumbbell Set     5.0      9495.25
39      1040   Aditya Verma             Dumbbell Set     4.7      1999.00
40      1041   Ishita Gupta             Coffee Maker     4.6      6648.10
47      1048     Sara Ahmed             Coffee Maker     5.0     10497.00
55      1056    Rohan Mehta             Dumbbell Set     5.0      3798.10
59      1060    Karan Joshi             Dumbbell Set     5.0      5397.30
60      1061     Alina Shah       Python Programming     5.0       711.55
62      1063     Aman Kumar            The Alchemist     4.8       449.10
64      1065      Zoya Khan       Python Programming     4.7      1273.30
65      1066      Dev Patel              Smart Watch     4.7      5938.20
68      1069  Vivaan Kapoor           Wireless Mouse     4.7      1708.10
72      1073     Sara Ahmed            Atomic Habits     4.6      2545.75
73      1074     Alina Shah            Atomic Habits     5.0       539.10
77      1078    Maryam Khan  Machine Learning Basics     4.7       899.10
79      1080   Aditya Verma                   Jacket     4.6      9996.00
85      1086     Arjun Nair                    Jeans     4.8      3228.30
90      1091    Hiba Sheikh            Atomic Habits     5.0      2995.00
94      1095    Maryam Khan               Power Bank     4.6      2398.00
99      1100      Kabir Ali    Data Science Handbook     4.8      4495.00

===== Highest Selling Order =====
Order ID: 1049
Customer: Ishita Gupta
Product: Running Shoes
Category: Sports
City: Mumbai
Sales: ₹13995.00

===== Best Performing Product =====
Product: Coffee Maker
Total Sales: ₹51610.25

===== Best Performing Category =====
Category: Sports
Total Sales: ₹136026.45

===== Most Used Payment Method =====
Payment Method: UPI
Number of Orders: 26

========== KEY OBSERVATIONS ==========
1. The dataset contains 100 orders and 13 columns.
2. Total sales generated from all orders is ₹447262.95.
3. The highest performing category based on total sales is Sports.
4. The product with the highest total sales is Coffee Maker.
5. The city with the highest total sales is Hyderabad.
6. UPI is the most commonly used payment method.
7. The average value of an order is ₹4472.63.
8. A total of 294 items were sold across 100 orders.